repos:
    - repo: https://github.com/python/black
      rev: 20.8b1
      hooks:
      - id: black
        types: [python]
        args: [--config=.pyproject.toml]
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
      - id: flake8
        types: [python]
        args: [--append-config=.flake8]
    - repo: https://github.com/PyCQA/isort
      rev: 5.6.4
      hooks:
        - id: isort
          types: [python]
          args: [--settings-file=.isort.cfg]
    - repo: https://github.com/softwaremill/scala-pre-commit-hooks
      rev: v0.3.0
      hooks:
        - id: sbt-unused-imports
          name: sbt-unused-imports
          types: [scala]
          args: [--scope=test:compile]
        - id: sbt-scalafmt
          name: sbt-scalafmt
          types: [scala]
        - id: sbt-wartremover
          name: sbt-wartremover
          types: [scala]
          args: [--warts=Warts.unsafe, --scope=test:compile]